spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minecraftserver?serverTimezone=UTC
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.sumuwen.boot.pojo
  mapper-locations: classpath:mapper/*.xml
